version: '3.6'
services:
  postgres:
    image: postgres:10-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: winnipeg
      POSTGRES_PASSWORD: winnipeg
      POSTGRES_DB: winnipeg
      DB_HOST: localhost
